### ISSUE TITLE
Weak dash lights

### ISSUE THREAD

**Issue by Joa1998** [jglovier/project-car#51]
I replaced my OEM dash lights bulps with led bulps. when testing the lights was very weak. tried the dimmer and the bulps got brighter when i turning the dimmer down and weaker when turning it up.
I Installed the old bulps back in and got no lights.
Fuses are good
Indicator and all other lights works
When i am trying to turn on my cluster lights the clock it will dim a little bit. i have tested the dimmer and it works.
Tried a new ground directley on a bulp, and light got bright again.  But it took out the fuse for the check engine light, oil lights and all warning lights several times when trying.

Any idea what it could be?

**Comment by jglovier** [comment]
@Joa1998 great question! I wish I knew. I have had the same problem. I tried replacing mine with LED, and two of them actually got brighter (the larger bulbs), but the smaller one's didn't at all. I don't know what to try next except maybe inspect the electrical wiring in the instrument cluster? ¯\_(ツ)_/¯

**Comment by jglovier** [comment]
LMK if you find a fix!

**Comment by Joa1998** [comment]
Just bought a ton of fuses and took a wire from my battery to the negative terminals of my cluster ( on the bulps ).
Two of them did not blow any of the fuses so i soldered a wire on to it and Connected it to my chassis. Works fine now. not sure why the ground went out but Works fine on the terminal i found. The other terminals took the fuses to my check engine light, oil lights etc.
Dimmer do not work, but i never use it anyway

Thanks

Sincerely Joackim

**Comment by jglovier** [comment]
Interesting. So maybe the dimmer is a common point of failure on these instrument clusters. 🤔
